[project]
name = "design-patterns"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black==24.1.1",
    "flake8==7.0.0",
    "pytest==8.0.0",
    "pytest-cov==4.1.0",
    "ruff==0.2.1",
]
