services:
  fastapi:
    image: web
    deploy:
      replicas: 2

  nginx:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/templates
    ports:
      - "8000:80"
    depends_on:
      - web
